# prometheus.yml

global:
  scrape_interval: 15s  # 기본 스크랩 간격
  evaluation_interval: 15s  # 규칙 평가 간격

# 알림 설정 (선택사항)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['localhost:9093']

# 데이터 수집 대상 설정
scrape_configs:
  # Prometheus 자체 메트릭 수집
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 예시: 추가 타겟 설정
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['localhost:9100']

  - job_name: 'order_service'
    static_configs:
      - targets: ['localhost:3001']  # order-service의 메트릭 엔드포인트

  - job_name: 'notification_service'
    static_configs:
      - targets: ['localhost:3002']  # notification-service의 메트릭 엔드포인트

  - job_name: 'gateway_service'
    static_configs:
      - targets: ['localhost:3003']  # gateway의 메트릭 엔드포인트